config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'sessions#new'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    
  if user.has_role? :admin
    can :manage, :all
  else
    can :read, Forum
    can :manage, Forum if user.has_role?(:manager, Forum)
    can :write, Forum, :id => Forum.with_role(:moderator, user).pluck(:id)
  end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  
  resourcify
  rolify
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  
  def feed
    # This is preliminary. See "Following users" for the full implementation.
    Micropost.where("user_id = ?", id)
  end
  
  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/eddb_controller.rb
class EddbController < ApplicationController
  def publish
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    # Before filters

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    #returns the full title on a per-page basis
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/eddb_helper.rb
module EddbHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
  
  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/eddb/publish.html.erb
<h1>Eddb#publish</h1>
<p>Find me in app/views/eddb/publish.html.erb</p>

app/views/eddb/user_new.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
    </aside>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to the Sample App</h1>

    <h2>
      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </h2>

    <%= link_to "Sign up now!", signup_path,
                                class: "btn btn-large btn-primary" %>
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <div class="collapse navbar-collapse navbar-ex1-collapse header">
      <%= link_to "ECOdrive - Fleet Control", "http://ecodrive-technology.com", id: "logo" %>
      <nav class="top-nav">
        <ul class="nav navbar-nav nav-top">
        	<% if current_user.has_role? :admin %>
        	<li id="fat-menu" class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= t 'views.header.change_app' %> <b class="caret"></b></a>
    		<ul class="dropdown-menu">
    			<li><%= link_to I18n.t('views.header.admin'), '#' %></li>
    			<li><%= link_to I18n.t('views.header.partner'), '#' %></li>
    			<li><%= link_to I18n.t('views.header.oem'), '#' %></li>
				<li><%= link_to I18n.t('views.header.distributer'), '#'%></li>
				<li><%= link_to I18n.t('views.header.client'), '#'%></li>
			</ul>
			</li>
			<% end %>
        	<li id="fat-menu" class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= t 'views.header.administration' %> <b class="caret"></b></a>
    		<ul class="dropdown-menu">
    			<li><%= link_to I18n.t('views.header.clients'), '#' %></li>
				<li><%= link_to I18n.t('views.header.comp_locations'), '#'%></li>
				<li><%= link_to I18n.t('views.header.cost_centers'), '#'%></li>
				<li><%= link_to I18n.t('views.header.veh_groups'), '#'%></li>
				<li><%= link_to I18n.t('views.header.driv_groups'), '#'%></li>
				<li><%= link_to I18n.t('views.header.vehicles'), '#' %></li>
				<li><%= link_to I18n.t('views.header.users'), '#' %></li>
				<li><%= link_to I18n.t('views.header.devices'), '#'%></li>
			</ul>
			</li>
			<li><%= link_to I18n.t('views.header.config'), '#' %></li>
			<li><%= link_to I18n.t('views.header.view'), '#' %></li>
			<% if current_user.has_role? :admin %>
			<li><%= link_to I18n.t('views.header.help'), '#' %></li>
			<% end %>
        	</ul>
        
        <ul class="nav pull-right navbar-nav nav-top">
		<li class="dropdown messages-dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= t 'views.header.massages' %> <span class="badge">7</span><b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li class="dropdown-header">7 New Messages</li>
				<li class="message-preview">
					<a href="#">
						<span class="avatar"><img src="http://placehold.it/50x50"></span>
                    	<span class="name">CVD</span>
                    	<span class="message">Hey there, I wanted to ask you something...</span>
                    	<span class="time"><i class="fa fa-clock-o"></i> 4:34 PM</span>
					</a>
				</li>
				<li class="divider"></li>
				<li class="message-preview">
					<a href="#">
                    	<span class="avatar"><img src="http://placehold.it/50x50"></span>
                    	<span class="name">John Smith:</span>
                    	<span class="message">Hey there, I wanted to ask you something...</span>
                    	<span class="time"><i class="fa fa-clock-o"></i> 4:34 PM</span>
					</a>
				</li>
				<li><a href="#">View Inbox <span class="badge">7</span></a></li>
			</ul>
		</li>
		<li class="dropdown alerts-dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <%= t 'views.header.alerts' %> <span class="badge">3</span> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Default <span class="label label-default">Default</span></a></li>
                <li><a href="#">Primary <span class="label label-primary">Primary</span></a></li>
                <li><a href="#">Success <span class="label label-success">Success</span></a></li>
                <li><a href="#">Info <span class="label label-info">Info</span></a></li>
                <li><a href="#">Warning <span class="label label-warning">Warning</span></a></li>
                <li><a href="#">Danger <span class="label label-danger">Danger</span></a></li>
                <li class="divider"></li>
                <li><a href="#">View All</a></li>
              </ul>
            </li>
            <li class="dropdown user-dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> John Smith <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#"><i class="fa fa-user"></i> Profile</a></li>
                <li><a href="#"><i class="fa fa-envelope"></i> Inbox <span class="badge">7</span></a></li>
                <li><a href="#"><i class="fa fa-gear"></i> Settings</a></li>
                <li class="divider"></li>
                <li><a href="#"><i class="fa fa-power-off"></i><%= link_to "Logout", signout_path, method: "delete" %></a></li>
              </ul>
            </li>
        </ul>
      </nav>
  </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
         <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav side-nav">
            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bar-chart-o"></i> <%= t 'views.side-nav.dashboard' %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to I18n.t('views.side-nav.fleet'), '#' %></li>
                <li><%= link_to I18n.t('views.side-nav.drivers'), '#' %></li>
              </ul>
            </li>
            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bar-chart-o"></i> <%= t 'views.side-nav.tracking' %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to I18n.t('views.side-nav.life_position'), '#' %></li>
                <li><%= link_to I18n.t('views.side-nav.track'), '#' %></li>
                <li><%= link_to I18n.t('views.side-nav.geofencing'), '#' %></li>
                <li><%= link_to I18n.t('views.side-nav.events'), '#' %></li>
              </ul>
            </li>
            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bar-chart-o"></i> <%= t 'views.side-nav.reporting' %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to I18n.t('views.side-nav.vehicles'), '#' %></li>
                <li><%= link_to I18n.t('views.side-nav.drivers'), '#' %></li>
                <li><%= link_to I18n.t('views.side-nav.fleet'), '#' %></li>
                <li><%= link_to I18n.t('views.side-nav.ranking'), '#' %></li>
                <li><%= link_to I18n.t('views.side-nav.comparison'), '#' %></li>
                <li><%= link_to I18n.t('views.side-nav.benchmark'), '#' %></li>
              </ul>
            </li>
            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bar-chart-o"></i> <%= t 'views.side-nav.maintenance' %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to I18n.t('views.side-nav.m_control'), '#' %></li>
                <li><%= link_to I18n.t('views.side-nav.m_plan'), '#' %></li>
                <li><%= link_to I18n.t('views.side-nav.settings'), '#' %></li>
              </ul>
            </li>
            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bar-chart-o"></i> <%= t 'views.side-nav.veh_condition' %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to I18n.t('views.side-nav.c_control'), '#' %></li>
                <li><%= link_to I18n.t('views.side-nav.diagnostics'), '#' %></li>
                <li><%= link_to I18n.t('views.side-nav.settings'), '#' %></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EcoDrive</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.3.min.css">
</head>
<body>
<% if signed_in? %>	
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<%= render 'layouts/header' %>
		<%= render 'layouts/sidebar' %>
	</div>    
    <div class="bar-left">
  			<button type="button" class="btn btn-default btn-sm left-btn"><span class="glyphicon glyphicon-chevron-left"></span></button>
  			<button type="button" class="btn btn-default btn-sm right-btn"><span class="glyphicon glyphicon-chevron-right"></span></button>
  			<center class="nav-name">Maintenance</center>
	</div>
    <div class="bar-right">
    	<select class="form-control app-select">
  			<option>Hersteller / Importeur</option>
  			<option>Niederlassung / Werksatt</option>
  			<option>Transportunternehmung</option>
		</select>	
    </div>
    <div id="wrapper">
    	
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
    <%= yield %>
    
    <%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
    
    </div>
<% else %>
<div class="container">
	<div class="jumbotron">
	 
		<%= yield %>
	 
	</div>
</div>
<% end %>    	
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
	  
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>